[package]
name = "libinject-linux"
authors = ["dustyw0lf"]
version = "0.1.0"
edition = "2021"
description = "Crate for process injection and fileless ELF execution on Linux."
repository = "https://github.com/dustyw0lf/libinject-linux"

[dependencies]
nix = { version = "0.29", features = ["ptrace", "mqueue"] }

[dev-dependencies]
ureq = "2.10.1"
